version: 2
updates:
  - package-ecosystem: pip
    directory: /project/video-parser/backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /project/video-parser/frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /project/video-parser/deploy
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
